### ISSUE TITLE
Error trying to Create Custom Dimensions

### ISSUE THREAD

**Issue by SimenHansen** [google/google-analytics-utilities#1]
I'm not able to copy any selected Custom Dimensions over to the Destination Property.

Using the UA Custom Dimensions - Modify both listings for template and destination are working. 
Selecting the CD indexes and a destination property the scripts throws this error when running the Universal Analytics > Custom Dimensions > Modify Custom Dimensions > Modify Custom Dimensions command.

![image](https://user-images.githubusercontent.com/3629563/134574245-ffa540e5-22ac-4d24-b0c5-bf95c0bb6ec2.png)
ReferenceError: templateCd is not defined

**Comment by jindlenz** [comment]
Hi, i'm having the same issue as Simen above.

**Comment by b-kuehn** [comment]
Thanks for raising this issue. This should be resolved with the most recent update. Please make a new copy of the template sheet to make use of the new code.
