### ISSUE TITLE
Feature Request - UA Goals with Funnels

### ISSUE THREAD

**Issue by salsus** [google/google-analytics-utilities#12]
Universal Analytics Goal List does not provide the standard export data from the [Management API](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/goals/list); the JSON returned provides the funnel for URL_Destination Goals. 

Insight into these funnel configurations can provide clearer direction when translating UA->GA4. It drives a strategic conversation with site owners around the uniqueness of a funnel's contents. It helps to decide between one `funnel_steps` event with parameters illustrating the different step numbers/names vs. individual `funnel_stepN` events for each one of the paths previously listed in the UA Goal.

**Management API:** with a 1 step required funnel as a short example
```
{
      "id": "11",
      "kind": "analytics#goal",
      "selfLink": "https://www.googleapis.com/analytics/v3/management/accounts/XXXXXXXX/webproperties/UA-XXXXXXXXX-8/profiles/XXXXXXXX/goals/11",
      "accountId": "XXXXXXXX",
      "webPropertyId": "UA-XXXXXXXX-8",
      "internalWebPropertyId": "XXXXXXXXXX",
      "profileId": "XXXXXXXXX",
      "name": "LP \u003e\u003e order",
      "value": 0,
      "active": true,
      "type": "URL_DESTINATION",
      "created": "2019-06-26T16:52:02.163Z",
      "updated": "2019-06-29T00:29:51.287Z",
      "parentLink": {
        "type": "analytics#profile",
        "href": "https://www.googleapis.com/analytics/v3/management/accounts/XXXXXXXX/webproperties/UA-XXXXXXXX-8/profiles/XXXXXXXX"
      },
      "urlDestinationDetails": {
        "url": "^\/summary\/(.*)confirmed",
        "caseSensitive": false,
        "matchType": "REGEX",
        "firstStepRequired": true,
        "steps": [
          {
            "number": 1,
            "name": "Zava",
            "URL": "^/zava\-"
          }
        ]
      }
    }
```
    
    **Utilities:** with no indication that a funnel exists for this URL Destination
![image](https://user-images.githubusercontent.com/3640465/231918945-ffb6cc45-c8d6-4a8f-8aa2-b8b120522d9f.png)

**Comment by b-kuehn** [comment]
This is a great point. Thanks for bringing this up.

Adding these array values into a spreadsheet format where each row is an individual goal is bit tricky. The simplest option would be to create a new column and write the "steps" JSON output for a given goal to a single cell in that goal's row. Would that address the use case you described?

It wouldn't be very convenient for anyone want to to make a goal with funnel steps from scratch from the sheet, but hopefully folks aren't doing that these days.

**Comment by salsus** [comment]
A single column as "hasFunnel" with "true/false" values would be minimally viable.
The JSON output into a single cell would be fantastic.

**Comment by b-kuehn** [comment]
Fixed in the latest release.
