### ISSUE TITLE
[UA -> GA4 Audiences migration] How to translate and setup custom events ?

### ISSUE THREAD

**Issue by cwdjankoski** [google/google-analytics-utilities#15]
Thank you to all the developers for the work on great tools to help with the UA -> GA4 migrations.
I have a question and I am not entirely sure if it belongs here - please redirect me to the correct please if it so.  

I am trying to migrate some UA custom audiences to GA4. I am having troubles to "translate" the custom events.  
The problem is that the migration tool succeeds to migrate the audience _seemingly_ but the new audience definition does not appear in GA4.

I am looking for some help or pointers on how to achieve the following.
If the customer came from a google/cpc click and landed on a category page `C` - then I would like to add this customer to an audience. Here `C` is just a name of a category like e.g. Music Vinyls. Also I have the category ID available in GA4 e.g. `123`.  

So far i have:
```
users::condition::sessionMedium=@cpc
condition::ga:sessionSource=@google

# in UA i used to have:
sequence::^ga:landingContentGroup4=@MusicVinyls

# in GA4 i tried with
sequence::eventName::categoryID=@123
```

I would be very grateful for some pointers to how to do this, what might be going wrong or where to go look further. Please let me know if this is not the appropriate channel for my ask as well. Thank you in advance.

**Comment by b-kuehn** [comment]
**Is this an issue with the GA Utilities or are you referring to [GA4 Migrator for Google Analytics](https://workspace.google.com/marketplace/app/ga4_migrator_for_google_analytics/472716783070)?** 
If you are talking about the GA4 Migrator, then I don't support that add-on and I don't really know why it might not be migrating a UA audience into GA4 properly.

**Do you need to recreate these audiences across several GA4 properties?**
The format you've written the above in looks like UA segment definitions that could be listed by the UA Management API. In GA4, audiences are defined by a filter clauses array, which is made up of one or more filter clause objects. Writing the GA4 audience definition in the way you have won't work. If you need to recreate this audience or something very similar across several properties, then I suggest creating a template version of this audience in the GA4 UI and then using GA Utilities to download the settings to a spreadsheet. You can then use GA Utilities to copy the audience settings across multiple properties without having to figure out how to properly format the filter clauses array by hand.

**Comment by cwdjankoski** [comment]
Oops yes you are right @b-kuehn - sorry, i have overseen this.
Thank you for the tips - i did not think of this and indeed would make things much easier.
thanks again, merry christmas and wish you nice end of the year 🎄
