### ISSUE TITLE
Extract users permissions UA and GA4

### ISSUE THREAD

**Issue by Rebellion720** [google/google-analytics-utilities#3]
How could the users and their permissions be extracted for the UA and GA4 accounts and copied to a sheet?

**Comment by b-kuehn** [comment]
It is possible to do this. I've done this in the past with UA, so I'll probably add both UA and GA4 user listing to GA Utilities sooner rather than later.

**Comment by Rebellion720** [comment]
> That functionality doesn't exist in the GA Utilities yet, but I will probably add it sooner rather than later.
> 
> Exactly how you would do it can vary, but one way would be to list all of the accounts you have access to, select which accounts you want to see user permissions for, loop through all the UA accounts, properties, and views and GA4 properties, and list out the direct permissions for each user at each level.

I don't know how I can do it, I don't know how to program it

**Comment by henkisdabro** [comment]
has this just become possible with recent updates to the Admin API? https://developers.google.com/analytics/devguides/config/admin/v1#user_permissions_management

**Comment by b-kuehn** [comment]
This is now available in the tool.
