### ISSUE TITLE
property lists multiple times

### ISSUE THREAD

**Issue by pschneider87** [google/google-analytics-utilities#6]
I have just created a copy of your tool, and tried to get an overview over my properties.
The script runs quite long for some reason.

Afterwards, in the property details list, I get the same properties multiple times:
![image](https://user-images.githubusercontent.com/17707309/194048675-90a1ab64-5f88-4cd9-8fc9-87869f4d05ee.png)

**Comment by b-kuehn** [comment]
In the accounts summaries sheet, did you select multiple properties from the same account before listing the property details? The property details feature works a bit differently than some of the other settings and lists all the properties under a given account, so you only need to select one row per account in the account summaries sheet.

**Comment by pschneider87** [comment]
Ok, makes sense. I did select all properties, so multiple per Account.
So the issue is me :)

Thanks for the heads-up

**Comment by b-kuehn** [comment]
Cool, thanks for the quick followup. I may try to update the readme to make this distinction clearer.
