### ISSUE TITLE
Pop is not defined

### ISSUE THREAD

**Issue by DarkoV** [google/google-analytics-utilities#7]
Hi,

After trying to list the properties I get a message: pop is not defined. Account is slected as instructed.

**Comment by ZordnajelA** [comment]
Same here,  `ReferenceError: pop is not defined` , doesn't matter if I select 1 or many properties. Hence the GA4 property details sheet doesn't get filled.

**Comment by b-kuehn** [comment]
This issue has been resolved in the code in the template sheet. An update to the github repo code will be forthcoming.
